name: MoneyDrop
main: Aleondev\Main
version: 1.0.0
api: [3.0.0,4.0.0]
load: POSTWORLD
author: Aleondev
description: "Moneydrop By Aleondev"

commands:
  payall:
    description: ยง4MoneyDrop
    usage: "/moneydrop <Betrag>"
    permission: moneydrop.command
